credentials:
  system:
    domainCredentials:
    - credentials:
      - string:
          description: "token for github repo"
          id: "gh-jenkins-tk"
          scope: GLOBAL
          secret: "{AQAAABAAAAAwAwOWN+8v5jzmiw1uRaZ7Y31xnV9C8RtfYz6SuyJCrk9BcYrfp51LoI2pTZawVNq7rwquPQFGBM0qaNVL58NO5Q==}"
      - basicSSHUserPrivateKey:
          id: "github-jenkins"
          privateKeySource:
            directEntry:
              privateKey: "{AQAAABAAAA1AoorIsr6SyLy+qgGxiYn9L90SpnWSae8X9sLGcDweDySSkwdunNaHpMPsPunQDGKO4H2JmfABJ6ggSVI0k8K9HI+oP+ArYFrQp6lKL4KHAsQsr7gJjJVLfsHh6ipNW+WnHqcIEuTraOqygJRqztH9FYlxVTWi0MiAwzs50pBD1obcqzZxSrfb4zdMsl0lyyDm3I+kp1t5zHy+PxxFbXrFOKkTCaBIYaIH7Pmi+VFHaELo651nG0/HXHf0ZCremVQcApK+3XHsCHUSwARvNT4tP2mz3XAFzQrp7YepqgGzK5UvsrRBDylXcwlGdDdSEAFwrS/TlAH0P+IehndJLT+cko0bFJw//gr8VQEgf1gjkW6hXQVrzYocqIi4KWelNYD7HeZhDyTVkgMlpYYpYSLWHFhlF7DMW6pI1zN9jLZtGXFzW6CWYkTdJcAd9OYCjamtWBnGMqz2r9Gulix2QNDR7S0rNd/yaFT32XNKG+/dTd2ja9wz5HtQLFo0DmB5GiGn+CXmj0XktsNYawApAzZJGQBDX6QYJnAp8G5UoMt4HXzeWX3mpZahy8bmgwMuj98U7w/6H3ZOrDx/Q1Hgna+IUDtcFIyO6YBZDZ69rU5EXvrMlHFSeztBeB6oO4sBw347bb/nb43A/V5za7FtyJAiR3Q5lNlV/q21l8agwtwFXszhS4CYAxeZs7GnJNvUecxF/5+QChv5VdL4L8yEkKFuYAb2oNAlzUeXUlbtgPypnaIzLtV8hlUC50lgphRxWDNcM4BV92qsgwldDDfdTgGaJUqYsV3GtIMI45WwbkiHr/1olUoTFCjG6hucq1pPRHgjVwYOEcwTTHx2qJoXlkMAuNuMEHGS8EUV9+/82TsOnFY9ivBy6+3NfmKQrvIUCq3d/oTOC8sdaRdChH0EAtabucNxV5aJz0ikfvuwAlVNGTKOVqYIy3z79GQQs/8yfcYMCRkdVysczCTRYhvaXkZ1J6b98kHZsbQFvR2FXAUTXYgKccDoS99CBrZa1fO1jjpajzr170yBQg5mw7QNMGg6NOgsFTr/SdEsl8IzbjTRqlBNVVvXRf8RTD8qGcHd6yUL26viFiRSTtFU69bnm2vERAzzkscfTRmA2ij3B9kZ7zDSJFDtR2Q1Y28366PJfHlYcIdAve1+tSujinZEZe12yuzQaOIpsySrcl6eU14m/+RA7EjvE6nuX1JfCVmMDP1mGSomSdy4lFHLGw0U318BIjKmfKePKI7qJbf4DO7aoWtu2WK3iHEgR9I7QMq7Nmbn00Bh+UEwM3UJGem0nCaLi3/s2hDxH2GEIPhZkZYzGTa4+BlEPvWl4kNtGcmIbhdcy2X5uQ90IzMnI+LsNaF6rRUl75NZcHMY6rz5HzuBGA7pgcxwaYMtLjMcZ2sNjwPnnmywDydVbJgZkuXCHFViqkq6WhBYNtoRnlR3X7lr4PCbm3GVeDLMFFKzEGHIDRY3g+naU4GyDd1uNMQMNY2F5ze1YGExC7j0uW7IWztfKZUsVWi1/ZiZwuxFrZUn53X47EwyDxJGrzFriJHLfswYqXVSNKv+h9uQPuY6ntX7qw7BfOtilt4merYUVIjRWLvh8XFSApnKn3jDecg//oA2dcuHOUPORQgdCbAHsoOrkak+DkEdmHN51plPR+hBqSYlx64BcRh3TnQFzIVqn3mU3rWygK5NzCX0Ge0rfxAeNptjYVii+TJKE7POOvs/xn0TuaTG9X6/OLPXsk7CEeB8rezAzu3MGm1U6OVxCzIrfjzVQNh+SI+smNKdAh7Rkr+6YMQt4+6yDwnyKGVy9s47q5fA6wLcd7sU8T3WhL5YwTwSfR9WwAdn1Ol34nTXqnixtL1xPq9yjrLlEOhMbQn2r1x6HJYM3ecENWklC6H3wz+yzYnxz1m3cEyWzbrx0wdPyZHDIRiXnE4v7q5mPz0brllRArTjA87eD7ciKoDYVKVjtF4WHjHjKRnOKOLV6+a9KfNDlfPpIolen1K15S21qwxDCppcV6E4iakpP53B34w/nHdJOWO0j4G6lDDgHIDkyksLZFr5QeSmV9WZdNCbPTB+9kBQ5LHlK4e8vh8aKGTIpI6SdBRWpxP4mWCpmrQ9GgyktMe5lbrezqqtQUq6Jns3UbqSwBDmUWDt0+DqeBL+vmAjeyp827sj4jTQ9e1su84Nh7ulu6wc5luQgiTWyj9r2GGxzfAUaPx8oxnkFOMLGqXSoZN+Ry+7Y5sE5I6sAGeqWriCPwZzs1hTz0pM9uip3D+U8w33lSPu3F+RqZxCp66toEX76mzNTsneh2WTxwxewUAJR9ggnoUZ6UfJ6NylYUMOzFtXaX59bSa+oBRRjyZBJydcWfkVN/+4XE4lrJG7SNKsACuOqoPY8eqa9dH/TqG79p5HI7flk8AkchktGFozO6hgsXg86RjBLEHsJktAJwSUAdc6PBcWE0Jwh6rHfPlqOUcwpcxT7mnZmi1+8znAFE2Uqsb6vAdU4TB2Ft3FxgSpVhTB6z1eKXHHAvtbR9cy1/dAtDKF5K3niufVaCz3bcJHk1OhzzLx9ZBhbiD1mdiIVlU2JlTety6HfyNw960+Wmux6lBA8lYqTFPzQO7F7ZPf7/K2xXO2pR4qC0amnrSWbr81JWkv3nL6ftrPAaPemxOdlf0YndOlwGOYZDtd3qjvo92kAuZ01dP8WFUh5gJtkPkYTd6FfUqd9O1KfqOemh0wTuKxM6kvTDzcdlcuzwm+fKnvB42ixYBp44rNj8lTSSFv/RY0nUNMLOavY6TMUG22bZlSIPAiLdnKo2v2rn5Q1Rs79h8rHbzoOAmAT6EQEXtbM6nrqW5wI+Fx55LDHPI3PvLytp3lZB+VvsdW4tESqPbBasG/xxVASGCvTzjy3KtKXEHy710oCZ4LzhvcitMQ406owRmHNH2iVwOp/EqM+xSgPXLdwwBKqn97FSxYogseEFMaAHMYNakRGT+vNL30QZzuihKkgvomhDXVwC4zrM6cbRQwCI5BBo65QekvcSXq+Gf6cypB1obSsZHHNpBywf52wi4yWlhHRFkcQDl0ylbEnZ0JRshlgTQ+6sxAD+XdRp81Wf5z2qeQCETau2t+QLteyDqNcxpnDQIiOPQTtf3OtfzH0FrS0GW+Ar0Qk3DnCAKXaUhBTTutCSF+MyfKJRQptivxajzruIFAoZGJPdthMkCOT0Z7sWu84xzDjA+fe6/HiZoNrkYKuAHqWtmRfT6iSJbHGnas3yfVrOpJ+ZCGkVp28rmhoiuZEbT0J62Z/vr/Y1bI0rVx5G7LBansfGZ4XncFJ+j3WCiovw/btNGFKUJH9xoHJjTV4E1GuSrCA2k6yw7TpHGrNX5eStLtAoyq+VivEXSGeJOp2LbIXWq0ZyYq8c2N/fNQ6k0efWL3uGV1vxXtbQaaxUYsa0IMBqIzL948b7lTX3sIvHQ+cczBNa25+ABvL1ZrwNvw/QU3ERw4GOfSW/dSoWqZ2shLnL2/85yigZGC3ydOwBiXprXF0DyEJoQV3T2j5EWgfCd6DvoK/q1ad0hOB/MXV323AOT4MRPleHyy7GnVOXEr9PnuWkAO6ygfrsVazM43TPBfsc8x1IUTGS7C1hL5WmnoXtcVYa+XVHJObxXuzcUB+71p/qfefpR5whY3inTcak4Oqyk405vcWDdSiETsuaIIraVkYnIW4vX3py6f5haZsarthoWMkzfcZTzjc3C5VyuGfacltXFV1UtxklksIEzjC1rAEk1hiWYMsgSLhyyRqyPr/PzinETFEdkSQivzQA9jzYcD1862+4g2RUw9E9seV4PEm9edXP9FVlkxNTs760Vbjfya7J7EgpTbgphB7bca015Qq5e2uzKiN/WoR1DQeExL9iv3QB92ZgXW8pIoePU4WmfceIv1UUD5djYL5wJrrrjLQxePuuERPNeOyx+894NWFq7OuNMt153Lc8EwyAL4MkyDsHNVKZa47/kNiRfucUbtN7DOVS1/0jEugvmaiDpM9+/ecKXUQIBtgteHP6OxpfM8wAeHtio8DJ3fErfoXdpbuYMQLNOMIkN6+eZylIjAY9P55H7vt60Cxo6yhNdi9vn7DHmjcZ75/4ynLuP4MLSdBBKhjqS2/wUVE281YvuXAIce9FSQ9S9WFbbProyYGR76CYEjnfENeNRRpgI0QJqwCY1+RZhVQSRocUoh/WQROFn3cC8f3Yfj+KMXRvlutZ4WDeR0MHsiNaFaot/g06dZe0DH0WfZBmPkz89gDMHH6/11ZmFfute/WBwZg6YtxOZfxKeVZ5W9R3M1E3VIuUNFfcvoblCeEPbnZpWdnQHygssROKcAzJCnOM3Y7t68A8aZQdgcOXWYgI2RXZ8zpbOzLDdKz0VggKfJ1qq/W/+RoLeyxbxaUAfozl0SSoIi6RY4jJe1cPcnGNVpeCg/NIp9bR4HoGrCP2CJq8AyuNhigJ7YB+5dFHd1pROStnYhOUc7xWepB8U1jnrBm0YTtloqQ5kMYXZJ/jv2f7vZmUlsL4f7Ix1rjE1sYwdSWHAixySpmPXt}"
          scope: GLOBAL
          username: "hjaijhoussem"
      - usernamePassword:
          id: "nexus"
          password: "jenkins3"
          scope: GLOBAL
          username: "jenkins"
      - string:
          id: "sonar-tk"
          scope: GLOBAL
          secret: "sqa_efdd8407e9501e13cc1d0e42de3f38815544792e"
      - basicSSHUserPrivateKey:
          id: "ansible-ssh-key"
          passphrase: "{AQAAABAAAA1AEEJJrzdcBDj3beRaD6qLs+kto9EIpT4N4fpCkI9ymvR6JdKOC5hBdPMb90KF5wxhy54TUpJ6n31q4zboZ3EvbHBl/SHUJXR/w6sYxFD8uPd0TGJzsHxI/zArC6vopuP452MD0LhiFVot5gsR4bOOQbwlL4dyTbjFLBp+mjkokt3NNLl1W39RV4TC9+ktNr84ZCyCZYTtflOMpppbbtcf/m3wLN6Y3UIKcvGLU5sfSYsnDiNz7ttIqiuzgSXmRrcJgAg85iWuTeqc0SdnMvm4kDZQVMM036mj104nBT/xUoB4H2fF7pMHjLtoK0cqqsiSWFX9hI0v0kXcgobPR10vPv3bpyWFgvdmS6aU+qLcUyD7WGvzw8KasX6JQFL1xdypxJp1o1rni/BEHt0hexZJu5pzJQzsUvi1feTAlt8H71ZAji0HHQaIwonfRxkoAoVkr7SvqBPEbDbzZcUuGgWZn4rlvrCtn+tHTUfS9vS+w+G3EaUfb9cVlrt3jsLBQ2aWkkUZPQesQdDDvc9BCNN9HOir6YIy3okuEKMiWyCTnpBlzPMuDDm5f3G1IBTaat3Tjll6QkVvi7of6tZ0qZkcR4ilByfeR+0sFzwFiGybcC2Xj+VmAD4UVq2nGRptKlaMYQeFPM03jgZLzvFXzf+N/zc2C070ZImVqG0MAI93xu5OJxTpWi76MnqmrzoSTKCgqHqvXW79Hgi/4kUbQX143zzFGPgZqdAWalY9cLDmqNiMhm9qnVjmHskY00TQtrCa962htpgX4u9r8toDDcFuwaHBRvaBv7HvTVn1uthfC3d4jXvKdVFkHL/gN2VyyOcV4EvEaRgq9N8yudFnsG5i1ZK5C63g5v5eGCV96N+drBEalr1npv5jbdWYHarUWwb48qmJWQ6h/w00+7mD3AUDpv2LUSP3DfgNepuYKpvIBZW2KHY8xF5+Z9wL4FTI33ztMiWHzhU438QMbIgI6Jn5To1hYD3syUyVKEGNWD4Q4X22GG9iQubvTGYPTgQ5nM/lyp3gblYezkulZxuMGGaYEGbv43NX0e4uIsWpLUgbk7BYE7lhTjImsGu6mbjd36f/gtW5TrlziAWaZ9D0m95GMZCpRYBqmkpnVNrb9/nHTqHdNtQQ75XfYPEWH97EYdRi7IeIkRE6bd8l7I/IrxVSDv0gG+EUQbA4R1moUFrcF7U/5BPu4DsIdhdCrwBY4YrpUpI6HxawSPxubg5sfFDFF5UVI8djc06lyxbYWgxV6esLeZVgcuCBovkGorZXkCkZxhhsmwq6xTqjc1uFGBN0I1mHoNpg3P7oygX1aKgx6dZQDy6KQD/saH2LtIujHl6QZ0FqxwLBcZJzelYj7UwpeTXfunABg+i6M+0oNWmw27XLTef9voJos11kWkZmGBb8LekLSkzCsIo2/ZxisHnlNP4v2pyjcwXDderSGrx/y9lQWD/dS1T2EsoeIvzCaAdkibKlL9kNOTsABmL3eVWV9TfSzZqFlM9aUSCiriEuWLjv8+BWZLcIMvVXY7JLXVHe+KKJ2PsKp5vTpmf2nR0HdROlWPuq1omwpiLDAJutEq3Et7/mcvUD0FHcu0rd9XSx+zMFic20QONe7Q2h6EdXyyzI2xwiNaT/4QLVvueWrX3yroBeylDsfL66UnmsrqldswQUacmdqtDLswA3VnUa6PHNvbEi+iC64HHxvkc7C4qXxsLSIso3GYFUYgYFvkAmPL4batiUvIKZghe+q9kJn043n0qFwWLOCI1dNy3H3C65S4ISg/lpVkzdjCUWiH6djoW7nNPgThFhOSaSTLNFEPs51Q0jppaVU81+5gwXYmSlT/CWFqDNLHzLvJ8QAK4hqFJDfmzIbHegxJ08NsWqj+LWOL3BZv7mBy4KRUTOV+5uandaRMUaajx9QiDuvXc01Cwn6jLr3mJNUgO7CCvp+4ouZtQuE9nVu4vS7MnuNCcbTqr3mCHxCdd/x1zF+UugeFzP624chcGKCeTFNoMcJuGaIygaqywu/W7TqVecyq1S4JFjuJWDqzFcULJX/6jP61K2Z7Q1dzar6StMHBcDtQl7Y9JjavSeAhWQ3/Qg421IYTCqi3QG1lymjIpYoL2C50lALq+WhAYsYEJsHKoJSrR2VMMHJ4dx6JGjL3q9b15gFAdrMKgJ8sOiWW9kCFbaZhqMmeizVXZ8rgPMz+Nz3mox9USN7pJhyB13QEUd/qhC0bMBfKNpa0AWDmVlyV+UOnZYn0hpshDwzB4hTwUY9F+DYC+1G7WFtRoPjLktRo9AvjHYHQVVfKiITT27lGDUP7L6jTEwd0fV6evT1yAXNwfThJ1EcPjJ14+KFGiqAIkFFP4bybGMF+wC2igRscKXeAd2W1YVW8zg8JjR/M6YXmIyIEn+q/LkWCLADJWQrsbvyAqyrsVJ1UZD2xV/iYFMB1WsQagHw6Nh9GHb5dkU+1oM68VwT7tqeZFB4a3mYcJoOq+VZcMOGRz6TXQaVn9wPxk8nsEusKhyslOPHlAIWadICdCUEISoG0f4sfIQw6QJ3go/2v/GE7nxoG13E5hgip6BLmhSefJCIOZvQ1k4XjFM3S9NRLP+L8Xek19NYwBUgBVuWq8vV26ZbULRXUxqwQDefSXHTdtbrc1F74T0R/aqkYjhCaYiE2Lq/G8Z1NJ9vP4OplzXbM11lG4zLA60NpkkpnxtH2Od4uB9gv7JIUeNOEW2O9vHkyplMuIMQ71PV0kPgVDwsCPcNIi6AyF6AEjuwixUEp36uLhwRB53yS6/HSFoDeOb8Tkt12oIXmaQCB0VTZCVXO/g9a+GHnp3BrJDY57/sQKCB7DTT2V/Ce24DTU9OFrGWrP8uloc2pIfhyn0Q4bfW/YZqLUjKW5aEJ5fRJ7XZok/GF/MKXD3CB2D4pQNNnO1gX6ZhF3Ci359wwu4s8y4I/3N+huOIiQu+O/pyVptUQh14UHE0a/ZxwiM9w/DedNbK7pdjNHNkqMFnVqjHBl7pgW7CPeC1qe3Dz8y2s8mPCrZEiWgfjajYXIov8fB/jBcJLRU/HmGvuj+b/rCG9F2GC7O0yim/uZdKtwblQX+Cd4HtGFXBUCg/jffskFC60mN6CnPtyfxuB2vjnGe29wYh8nSciPuFk7fKiBCd4n4AtR7diLTNkFJCVeNaX+C5hByHqu9Tb9cqTIr6H7w5Ik7UkgCf2eGRfVw+f0MygHXaqQF1l1UxHCLdxuPkwBeYXDEttug1YJeOz71An6q5+BikhtU9bjVxGCmzysr4c8oHsipksVnpn9UmD8Sx9BThnZzFYtClEnFU3h9uLqeUgKe+KASAgDnzcZXXEcDV18wihuddVbaAeugfwf7pmr477fOemwuyjwfVjnBid/2IE+pqA+nbIFmMuhzL8LDmZ0YUo+RwOnRYIeOn7rcS+xuH6UJarVmqATi9mi1Pdd4SBMvz5cQcbX/W28c/gSUwvK/zi1s29sHXQOq3mSpgUP9hu+AV8Dfc2ZVbq1sN1u9XL5baP2yVGscU7uSDH3E99iDfRoG57dEaQzQ+ATUR18qjOi+OYRJuA0qyO/g4UZiUvjkN6WFG6G65kw+bwSldx5cMAuhEdwB3jXPc0dVryHXp5hdB0ykmh8n6G/AJ6Ascc6DoHr2rfMmUxLhx5Un69C0/M7+4ltxy08XMPzpjFWxL+Zgp+Ld2+G++4CcFXof70UZr2lMiEkNLKZd0Vg6vuBMJfZ+2VGby+QTRPfBt+e7qJpxkmeES5g5BdHljctdGuTNPHvumLOa7LVgdi36WaRVq/eNkb6SFx9iDeY9GIwD2AiTkkTHDSwBdbq7kXnuDolR99jUIqb5Ee1no6lV/frWifMgFF2xyg9wwd04VnnvGX6urrUnIElLxMmmdYSnt1YLfH51YLnnO64yQWXK2q90ghj62SLwZBVbtxttYcZQYl5WNT2H0Mli8SthqBtLGnPAjOMgRNMug+kd07XZ5C4CrerR3oegMyoPEgJ0bfe3SMu/P7uPc8u3eKi0hcvLMXmH/LKKe8Qvsj7xcyKlSAsZm1lyxcUHRwBPmpsNjP14cK6iTz8yRcqoHa3s6h1mz6LQFH5Eyc85eXgZjrHU49lyFe/w8+JQdANts8gkJKwZyFusvnCghOeu2bco5rn2edYYqT7ILOWEwAbDB0pa0GGIi6zoqPla9nUPlW+6l8DeUTXhWJtPdmvUVcg4IvU00ILbxvl/7h525AfCe2/hZbvSLQee83msNbVwNBLwpPWZEExYdcLY7Ttr2QKO5xhrwaUpviP3sF5vhjOlw/8XLQDT+xXxFq4CBvB6IT++G9CPXSpSCqU0Z+naMVd6xRjdC8zb4C6wJUZR9Q5CYCHWBI0mgxy74GqygG4ioP9bD9jFWD/inwJQogH7Fd1RofWoGkuoFZfL0wQFvV5V5ExDAddq5uOH8BpN9v6ThapDTLBvQdGnamrvpr0QR/fIfUwdB6Nw4m1FaZc5QTNNFnqX5P3ggO2cTN1AuMm4MwR1+dXuOWk1Q24LvnG537kHJqsvg7fqN3xM1IRveHhd}"
          privateKeySource:
            directEntry:
              privateKey: "{AQAAABAAAAAQeFxvS57Czf0NPSJ14xihVXo35JyLiJbYWxKdCzdSrpA=}"
          scope: GLOBAL
          username: "root"
jenkins:
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  disableRememberMe: false
  disabledAdministrativeMonitors:
  - "hudson.util.DoubleLaunchChecker"
  labelAtoms:
  - name: "built-in"
  markupFormatter: "plainText"
  mode: NORMAL
  myViewsTabBar: "standard"
  nodeMonitors:
  - "architecture"
  - "clock"
  - diskSpace:
      freeSpaceThreshold: "1GiB"
      freeSpaceWarningThreshold: "2GiB"
  - "swapSpace"
  - tmpSpace:
      freeSpaceThreshold: "1GiB"
      freeSpaceWarningThreshold: "2GiB"
  - "responseTime"
  numExecutors: 2
  primaryView:
    all:
      name: "all"
  projectNamingStrategy: "standard"
  quietPeriod: 5
  remotingSecurity:
    enabled: true
  scmCheckoutRetryCount: 0
  slaveAgentPort: 50000
  updateCenter:
    sites:
    - id: "default"
      url: "https://updates.jenkins.io/update-center.json"
  views:
  - all:
      name: "all"
  viewsTabBar: "standard"
globalCredentialsConfiguration:
  configuration:
    providerFilter: "none"
    typeFilter: "none"
appearance:
  prism:
    theme: PRISM
security:
  apiToken:
    creationOfLegacyTokenEnabled: false
    tokenGenerationOnCreationEnabled: false
    usageStatisticsEnabled: true
  cps:
    hideSandbox: false
  gitHooks:
    allowedOnAgents: false
    allowedOnController: false
  gitHostKeyVerificationConfiguration:
    sshHostKeyVerificationStrategy: "knownHostsFileVerificationStrategy"
  scriptApproval:
    forceSandbox: false
unclassified:
  buildDiscarders:
    configuredBuildDiscarders:
    - "jobBuildDiscarder"
  buildStepOperation:
    enabled: false
  email-ext:
    adminRequiredForTemplateTesting: false
    allowUnregisteredEnabled: false
    charset: "UTF-8"
    debugMode: false
    defaultBody: |-
      $PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS:

      Check console output at $BUILD_URL to view the results.
    defaultContentType: "text/plain"
    defaultSubject: "$PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS!"
    defaultTriggerIds:
    - "hudson.plugins.emailext.plugins.trigger.FailureTrigger"
    maxAttachmentSize: -1
    maxAttachmentSizeMb: -1
    precedenceBulk: false
    throttlingEnabled: false
    watchingEnabled: false
  enrichedSummaryConfig:
    enrichedSummaryEnabled: false
    httpClientDelayBetweenRetriesInSeconds: 1
    httpClientMaxRetries: 3
    httpClientTimeoutInSeconds: 1
  fingerprints:
    fingerprintCleanupDisabled: false
    storage: "file"
  gitHubConfiguration:
    apiRateLimitChecker: ThrottleForNormalize
  gitHubPluginConfig:
    hookUrl: "http://localhost:8081/github-webhook/"
  globalTimeOutConfiguration:
    operations:
    - "abortOperation"
    overwriteable: false
  injectionConfig:
    allowUntrusted: false
    checkForBuildAgentErrors: false
    enabled: false
    enforceUrl: false
    gradleCaptureTaskInputFiles: true
    injectCcudExtension: false
    injectMavenExtension: false
    mavenCaptureGoalInputFiles: true
  junitTestResultStorage:
    storage: "file"
  location:
    adminAddress: "l'adresse n'est pas encore configurée <nobody@nowhere>"
    url: "http://localhost:8081/"
  mailer:
    charset: "UTF-8"
    useSsl: false
    useTls: false
  pollSCM:
    pollingThreadCount: 10
  scmGit:
    addGitTagAction: false
    allowSecondFetch: false
    createAccountBasedOnEmail: false
    disableGitToolChooser: false
    hideCredentials: false
    showEntireCommitSummaryInChanges: false
    useExistingAccountWithSameEmail: false
  sonarGlobalConfiguration:
    buildWrapperEnabled: false
    installations:
    - credentialsId: "sonar-tk"
      name: "mysonar"
      serverUrl: "http://sonarqube:9000"
      triggers:
        skipScmCause: false
        skipUpstreamCause: false
  timestamper:
    allPipelines: false
    elapsedTimeFormat: "'<b>'HH:mm:ss.S'</b> '"
    systemTimeFormat: "'<b>'HH:mm:ss'</b> '"
tool:
  ansible:
    installations:
      - home: "/usr/bin/ansible"
        name: "ansible-home"
      - name: "ansible:latest"
        properties:
          - installSource:
              installers:
                - batchFile:
                    command: "sudo apt update \r\nsudo apt install -y software-properties-common\r\
                  \nsudo apt-add-repository --yes --update ppa:ansible/ansible\r\nsudo\
                  \ apt install -y ansible"
                    toolHome: "/usr/bin/ansible"
  git:
    installations:
    - home: "git"
      name: "Default"
  maven:
    installations:
    - name: "3.9.5"
      properties:
      - installSource:
          installers:
          - maven:
              id: "3.9.5"
  nodejs:
    installations:
      - name: "nodejs-18"
        properties:
          - installSource:
              installers:
                - nodeJSInstaller:
                    id: "18.20.5"
                    npmPackagesRefreshHours: 72
  mavenGlobalConfig:
    globalSettingsProvider: "standard"
    settingsProvider: "standard"
  sonarRunnerInstallation:
    installations:
    - name: "Sonar"
      properties:
      - installSource:
          installers:
          - sonarRunnerInstaller:
              id: "6.2.1.4610"
jobs:
  - script: >
      multibranchPipelineJob('car-pooling-fe-multibranch') {
        branchSources {
          git {
            id('car-pooling-backend-git')
            remote('https://github.com/hjaijhoussem/Car-pooling-backend.git')
            credentialsId('github-jenkins')
          }
        }
        factory {
          workflowBranchProjectFactory {
            scriptPath("Jenkinsfile")
          }
        }
      }

  - script: >
      pipelineJob('car-pooling-be') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/hjaijhoussem/Car-pooling-backend.git')  
                  credentials('github-jenkins')
                }
                branch('*/main') 
              }
            }
            scriptPath("Jenkinsfile") 
            lightweight()  
          }
        }
      }
  - script: >
      pipelineJob('car-pooling-fe') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/hjaijhoussem/Car-pooling-frontend.git')  
                  credentials('github-jenkins')
                }
                branch('*/main') 
              }
            }
            scriptPath("carpools/Jenkinsfile") 
            lightweight()  
          }
        }
      }
    
