version: '3.3'
services:

  nginx-nexusproxy:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    image: nginx-nexusproxy
    container_name: nginx-nexusproxy
    volumes:
      - ./nginx/nexuskey.pem:/etc/nginx/external/nexuskey.pem
      - ./nginx/nexuscert.crt:/etc/nginx/external/nexuscert.crt
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '443:443'
      - '6666:6666'
      - '7777:7777'
    links:
      - nexus
    command: [ 'nginx', '-g', 'daemon off;' ]
    networks:
      - pipeline

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONARQUBE_ADMIN_PASSWORD=Admin-admin1
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp
    networks:
      - pipeline

  nexus:
    image: sonatype/nexus3
    container_name: nexus
    ports:
      - '8082:8081'
    networks:
      - pipeline
    volumes:
      - nexus-data:/nexus-data

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    image: "hjaiejhoussem/jenkins:casc-custom"
    container_name: jenkins_casc
    ports:
      - '8081:8080'
      - '50000:50000'
    volumes:
      - './plugins.txt:/usr/share/jenkins/ref/plugins.txt'
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_home:/var/jenkins_home
      - ./casc.yaml:/var/jenkins_home/casc.yaml
      - /usr/bin/ansible:/usr/bin/ansible
    networks:
      - pipeline
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc.yaml
    depends_on:
      - nexus

networks:
  pipeline:
    driver: bridge
volumes:
  sonarqube_conf:
    driver: local
  sonarqube_data:
    driver: local
  sonarqube_extensions:
    driver: local
  sonarqube_logs:
    driver: local
  sonarqube_temp:
    driver: local
  nexus-data:
    driver: local
  jenkins_home:
    driver: local
