FROM nginx:stable

RUN mkdir -p /etc/nginx/external

#COPY nginx/nexuskey.pem /etc/nginx/external/nexuskey.pem

#COPY nginx/nexuscert.crt /etc/nginx/external/nexuscert.crt

COPY nginx/nginx.conf /etc/nginx/nginx.conf